apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
  namespace: monitoring
  labels:
    app: blackbox-exporter
data:
  blackbox.yaml: |
    modules:
      http_2xx:
        http:
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2
          valid_status_codes:
            - 200
            - 204
            - 403
        prober: http
        timeout: 10s
