kind: Service
apiVersion: v1
metadata:
  name: blackbox-service
  namespace: monitoring
  labels:
    app: blackbox-exporter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9115
      protocol: TCP
  selector:
    app: blackbox-exporter
