kind: Service
apiVersion: v1
metadata:
  name: blackbox-service
  namespace: monitoring
  labels:
    app: blackbox-exporter
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9115'  
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9115
      protocol: TCP
  selector:
    app: blackbox-exporter
