apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: prometheus-pvc
 namespace: monitoring
spec:
 storageClassName: gold
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 10Gi
