kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager-templates/*.tmpl'
    route:
      receiver: pagerduty-demo
      group_by: ['alertname', 'cluster', 'priority']
      group_wait: 30s
      repeat_interval: 30m
      routes:
        - receiver: multiple-demo
          matchers:
            - severity="critical"
          group_wait: 10s
          repeat_interval: 5m

    receivers:
    - name: pagerduty-demo
      pagerduty_configs:
        - service_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    - name: multiple-demo
      pagerduty_configs:
        - service_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          send_resolved: true
      slack_configs:
      - api_url: https://hooks.slack.com/services/XXXXXXXXXXX/YYYYYYYYYYY/000000000000000000000000
        channel: '#obssim-demo'
        color: '{{ template "slack.color" . }}'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true
        actions:
          - type: button
            text: 'Runbook :green_book:'
            url: '{{ (index .Alerts 0).Annotations.runbook_url }}'
          - type: button
            text: 'Query :mag:'
            url: '{{ template "__alertmanagerURL" . }}'
          - type: button
            text: 'Dashboard :chart_with_upwards_trend:'
            url: '{{ (index .Alerts 0).Annotations.dashboard_url }}'
          - type: button
            text: 'Silence :no_bell:'
            url: '{{ template "__alert_silence_link" . }}'
