apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-templates
  namespace: monitoring
data:
  default.tmpl: |
    {{/* Alertmanager name */}}
    {{ define "__alertmanager" }}AlertManager{{ end }}

    {{/* Alertmanager external link */}}
    {{ define "__alertmanagerURL" }}{{ .ExternalURL }}/#/alerts?receiver={{ .Receiver }}{{ end }}

    {{/* Alertmanager silence link */}}
    {{ define "__alert_silence_link" }}{{ .ExternalURL }}/#/silences/new?filter=%7B{{ range .CommonLabels.SortedPairs }}{{ if ne .Name "alertname" }}{{ .Name }}%3D"{{ .Value }}"%2C%20{{ end }}{{ end }}alertname%3D"{{ .CommonLabels.alertname }}"%7D{{ end }}

    {{/* Severity of the alert */}}
    {{ define "__alert_severity" }}{{ if eq .CommonLabels.severity "critical" }}*Severity:* `Critical` {{ else if eq .CommonLabels.severity "warning" }}*Severity:* `Warning` {{ else if eq .CommonLabels.severity "info" }}*Severity:* `Info` {{ else }}*Severity:* :question: {{ .CommonLabels.severity }}{{ end }}{{ end }}

    {{/* Subject of the alert */}}
    {{ define "__subject" }}ALERT-[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }}{{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}{{ end }}

    {{/* Text of the alert */}}
    {{ define "__text_alert_list" }}{{ range . }}Labels:
    {{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}
    {{ end }}Annotations:
    {{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}
    {{ end }}Source: {{ .GeneratorURL }}
    {{ end }}{{ end }}
  pagerduty.tmpl: |
    {{ define "pagerduty.default.description" }}{{ template "__subject" . }}{{ end }}

    {{ define "pagerduty.default.client" }}{{ template "__alertmanager" . }}{{ end }}

    {{ define "pagerduty.default.clientURL" }}{{ template "__alertmanagerURL" . }}{{ end }}

    {{ define "pagerduty.default.instances" }}{{ template "__text_alert_list" . }}{{ end }}
  slack.tmpl: |
    {{ define "slack.default.title" }}{{ template "__subject" . }}{{ end }}
    {{ define "slack.default.username" }}{{ template "__alertmanager" . }}{{ end }}
    {{ define "slack.default.pretext" }}{{ end }}
    {{ define "slack.default.titlelink" }}{{ template "__alertmanagerURL" . }}{{ end }}
    {{ define "slack.default.iconemoji" }}{{ end }}
    {{ define "slack.default.iconurl" }}{{ end }}
    {{ define "slack.default.text" }}{{ end }}
    {{ define "slack.default.fallback" }}{{ template "slack.default.title" . }} | {{ template "slack.default.titlelink" . }}{{ end }}

    {{/* Title of the Slack alert */}}
    {{ define "slack.title" }}ALERT-[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}{{ end }}

    {{/* Color of Slack attachment (appears as line next to alert )*/}}
    {{ define "slack.color" }}{{ if eq .Status "firing" }}{{ if eq .CommonLabels.severity "warning" }}#FFFF00{{ else if eq .CommonLabels.severity "critical" }}#FF0000{{ else }}#439FE0{{ end }}{{ else }}#00FF00{{ end }}{{ end }}

    {{/* The text to display in the alert */}}
    {{ define "slack.text" }}{{ template "__alert_severity" . }}{{ if (index .Alerts 0).Annotations.summary }}{{ "\n" }}*Summary:* {{ (index .Alerts 0).Annotations.summary }}{{ end }}{{ range .Alerts }}{{ if .Annotations.description }}{{ "\n" }}*Description:* {{ .Annotations.description }}{{ "\n" }}{{ end }}{{ if .Annotations.message }}{{ "\n" }}*Message:* {{ .Annotations.message }}{{ "\n" }}{{ end }}{{ end }}{{ end }}
